import "./globals.css"
import {roboto} from "@/fonts/fonts";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={`${roboto.className}`}>{children}</body>
    </html>
  )
}
